export const BOOK_CATEGORIES = [
  "Adventure",
  "Biography",
  "Children's",
  "Classics",
  "Crime",
  "Dystopian",
  "Fantasy",
  "Historical Fiction",
  "History",
  "Horror",
  "Humor",
  "Mystery",
  "Non-fiction",
  "Philosophy",
  "Poetry",
  "Romance",
  "Science",
  "Science Fiction",
  "Thriller",
  "Travel",
  "Young Adult",
] as const;