create table public.books (
    id bigint generated by default as identity primary key,

    title text not null,
    author text not null,

    published_year integer,

    category text,

    series_number integer default 0,

    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);